<?php
/*
    ## https://book.cakephp.org/3.0/en/views/helpers/paginator.html#template-names ##
 
    nextActive: The active state for a link generated by next().
    nextDisabled: The disabled state for next().
    prevActive: The active state for a link generated by prev().
    prevDisabled: The disabled state for prev()
    counterRange: The template counter() uses when format == range.
    counterPages: The template counter() uses when format == pages.
    first: The template used for a link generated by first().
    last: The template used for a link generated by last()
    number: The template used for a link generated by numbers().
    current: The template used for the current page.
    ellipsis: The template used for ellipses generated by numbers().
    sort: The template for a sort link with no direction.
    sortAsc: The template for a sort link with an ascending direction.
    sortDesc: The template for a sort link with a descending direction.
 */

/**
 * 
 * Pakgon custom template pagination
 * @author sarawutt.b
 */
return [
    'number' => '<li class="page-item"><a class="page-link waves-effect waves-effect" href="{{url}}">{{text}}</a></li>',
    'current' => '<li class="page-item active"><a class="page-link waves-effect waves-effect" href="#">{{text}}</a></li>',
    'nextActive' => '<li class="page-item"><a aria-label="Next" href="{{url}}">{{text}}</a></li>',
    'nextDisabled' => '<li class="page-item page-item-next disabled"><a aria-label="Next"><span aria-hidden="true">»</span></a></li>',
    'prevActive' => '<li class="page-item"><a aria-label="Previous" href="{{url}}">{{text}}</a></li>',
    'prevDisabled' => '<li class="page-item page-item-prev disabled"><a aria-label="Previous"><span aria-hidden="true">«</span></a></li>',
    'first'=>'<li class="page-item-first page-item"><a class="page-link waves-effect waves-effect" href="{{url}}">{{text}}</a></li>',
    'last'=>'<li class="page-item-last page-item"><a class="page-link waves-effect waves-effect" href="{{url}}">{{text}}</a></li>'
];